### ISSUE TITLE
Benefits of Creating Design Prototype in Adobe XD for UI Design Challenges

### ISSUE THREAD

**Issue by hasanozie** [topcoder-platform/thrive-submit#118]
Track Category: Design

[Hasanozie - Benefits of Creating Design Prototype in Adobe XD for UI Design Challenges.docx](https://github.com/topcoder-platform/thrive-submit/files/3989445/Hasanozie.-.Benefits.of.Creating.Design.Prototype.in.Adobe.XD.for.UI.Design.Challenges.docx)

**Comment by kkartunov** [comment]
passed checks

**Comment by fajarmln** [comment]
This article needs more research on how doing prototyping in adobe xd can bring benefit for user in ui design challenges? what is the differences if we do the prototyping in marvel instead of xd? why prototyping is important? this article lacks of curiousity and exploration and only focusing on how to create xd prototype which not really useful for design challenge at topcoder since we use marvel app (xd prototype export most of the time will messed up in marvel, make sure to check it too)

**Comment by hasanozie** [comment]
Hi bang @fajarmln 
Thank you for reviewing this article :)
I have corrected this article according to the advice you gave.

[Hasanozie - Benefits of Creating Design Prototype in Adobe XD for UI Design Challenges New.docx](https://github.com/topcoder-platform/thrive-submit/files/4000649/Hasanozie.-.Benefits.of.Creating.Design.Prototype.in.Adobe.XD.for.UI.Design.Challenges.New.docx)

**Comment by fajarmln** [comment]
its' not good enough. You only revise one or two sentences about the Marvel and go with the same content again. FYI, Marvel have a desktop and also a mobile app that you can use for creating the prototype, so your articles can be misleading, also, the content details of this article can be found easily in the internet, so no value for THRIVE. I will reject this article, thank you.
