### ISSUE TITLE
Mandatory Questions For Clients Before Starting Graphic Design Project

### ISSUE THREAD

**Issue by hasanozie** [topcoder-platform/thrive-submit#157]
Track Category: Design

[Hasanozie - Mandatory Questions For Clients Before Starting Graphic Design Project.docx](https://github.com/topcoder-platform/thrive-submit/files/3993355/Hasanozie.-.Mandatory.Questions.For.Clients.Before.Starting.Graphic.Design.Project.docx)

**Comment by kkartunov** [comment]
passed checks

**Comment by s-kaur** [comment]
Thank you for submitting the articles, there are some interesting points here however this topic probably not the best fit for Topcoder, we don't have this kind of model of direct communication to client this far more beneficial for freelancer, and not bringing much value to the thrive content, and I'd like to add few tips here, let's focus on quality of writing instead of quantity of articles submissions?

**Comment by hasanozie** [comment]
Hi @s-kaur 
Thank you for reviewing this article :)
