### ISSUE TITLE
New Thrive Article

### ISSUE THREAD

**Issue by madhurgupta10** [topcoder-platform/thrive-submit#272]
**Track**
Topcoder

**Author**
madhurgupta10

**Link**
https://docs.google.com/document/d/1lkzQqlo7xtLdAdW2hDSablMIhzI5JsT2BpXSs4nVfD4/edit?usp=sharing

**Topic:**
How to get Paid in India on Topcoder.

**Article Available**
Yes

**Comment by kkartunov** [comment]
passed checks

**Comment by harshitmehta123** [comment]
Hey @madhurgupta10 I had already paid to you for this during last year India regionals - so we have this doc :) - We cannot publish it (because financial information remains different for everyone ), however, it sometimes helps me with a few student based members who have the same condition as mentioned in this doc.

**Comment by madhurgupta10** [comment]
@harshitmehta123 Hi, No issues. Thanks for the clarification. I would write other Thrive article :)

**Comment by harshitmehta123** [comment]
Thanks, man! Waiting for your article :)
