### ISSUE TITLE
Demonstrate learning process of  Natural Language Processing

### ISSUE THREAD

**Issue by t0070926** [topcoder-platform/thrive-submit#33]
[Demonstrate learning process of  Natural Language Processing.docx](https://github.com/topcoder-platform/thrive-submit/files/3930373/Demonstrate.learning.process.of.Natural.Language.Processing.docx)

**Comment by kkartunov** [comment]
Passed PCheck

**Comment by harshitmehta123** [comment]
Can you add an example and show each phase with a code snippet? @t0070926

**Comment by t0070926** [comment]
[Basics of Natural Language Processing algorithm.docx](https://github.com/topcoder-platform/thrive-submit/files/3963367/Basics.of.Natural.Language.Processing.algorithm.docx)

**Comment by t0070926** [comment]
changed title added required details as you suggested

**Comment by harshitmehta123** [comment]
Hey @t0070926, I think you should pick an example - of some text or Data and then after each step you explain you should show the code snippet for that and also how the Data is changing after each step. 

For example

**Morphological Processing(MP)**
It is the initial phase of NLP. And the purpose of this phase is to break chunks of language input into sets of token corresponding to paragraphs, sentences, and words. For example, a name like "uneasy" can split into two sub-word tokens as "un-easy." process.

// Here you should show how we are achieveing this and what happens when we run that code. Why will it help us and why did we split the words?
