### ISSUE TITLE
Distributed transactions in the microservices architectures

### ISSUE THREAD

**Issue by kavukcutolga** [topcoder-platform/thrive-submit#56]
Please evaluate the article:

Track: Development

https://docs.google.com/document/d/1iMUL85FH1xG0KwJPvZrr1EPoz2dJHsy8-Ey_OC5mJcI/edit?usp=sharing

**Comment by kkartunov** [comment]
passed PCheck

**Comment by billsedison** [comment]
@kavukcutolga Can you add more figures to describe the Saga pattern? By reading through the whole article, I still don't understand how Saga pattern benefits in the distributed transactions in the microservices architecture.

Maybe you need to add more figures, and describe its advantages more detailedly. Like how it compares with 2PC etc.

**Comment by kavukcutolga** [comment]
I am working on feedbacks please keep the issue open. Will

**Comment by billsedison** [comment]
@kkartunov How is the progress?

**Comment by kavukcutolga** [comment]
I will finish it before 31/12

**Comment by kavukcutolga** [comment]
@billsedison @kkartunov , please see the updates to the article. Please also note that the article not only explains the Saga patterns but also suggests two different frameworks for the implementation. So, I agree it should explain the Saga pattern clearly but the intention is not deep-diving into the pattern

**Comment by billsedison** [comment]
@kavukcutolga Sorry for the late reply

Can you elaborate on more details about how Orchestrator handles the failure cases, instead of just giving a picture?

![image](https://user-images.githubusercontent.com/5657467/72064048-05556100-3316-11ea-9d63-b0a0ab25f0bb.png)

Just by looking at this article, I still don't understand how Saga patterns work.

And for NETFLIX CONDUCTOR and ZEEBE, it's the same, the description is TOO BRIEF. Maybe you can just write Saga pattern in this article, and elaborate on its principles and how it resolves the transaction consistency issues among multiple microservice instances.

**Comment by kkartunov** [comment]
Closing this due to long inactivity.
