### ISSUE TITLE
List of Websites That Will Help You Compete in UI Design Challenges

### ISSUE THREAD

**Issue by hasanozie** [topcoder-platform/thrive-submit#78]
Track Category: Design

[Hasanozie - List of Websites That Will Help You Compete in UI Design Challenges.docx](https://github.com/topcoder-platform/thrive-submit/files/3959606/Hasanozie.-.List.of.Websites.That.Will.Help.You.Compete.in.UI.Design.Challenges.docx)

**Comment by kkartunov** [comment]
passed PCheck and min len check

**Comment by Dara-K** [comment]
Hi! I see you put a lot of effort into this article and I appreciate it, but I don't think it brings up too much value and that's because most of the websites are included in the Topcoder policies.
**- Adobe Stock**
**- Shutterstock**
**- Unsplash**
**- Pexels**
The members are required to use photos only from them as mentioned in the [Topcoder Policies](https://help.topcoder.com/hc/en-us/articles/217481408-Policy-for-Stock-Artwork-in-Design-Submissions) so they will check them from Topcoder site rules.

**- Flaticon**
Same for Flaticon ([Topcoder Icon Policy](https://help.topcoder.com/hc/en-us/articles/360007546013-Policy-for-Icons-in-Design-Submissions))

**- Loremipsum.io**
Ideally, in Topcoder design challenges, is best not to use lorem ipsum text as we should come up with content relevant to each customer's industry so the customer resonates with the info from there.

**- uinames**
Right now, for the mainstream design tools, Sketch has plugins for generating names of persons and for Adobe XD it is very easy to just drag and drop some names saved in a spreadsheet and then continue to reuse those.

**- Brainyquote**
I don't think this brings too much value to a design

I agree that Articlegenerator.org, Fontpair.co, Gradienthunt and Colorhunt are good websites for designers, but they are not enough for an article.

**Comment by hasanozie** [comment]
Hi @Dara-K ,
Thank you for reviewing this article :)
